version: "3.9"

services:
  app:
    image: alanwakeking/propusk-system:latest
    container_name: propusk_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL:-}
      POSTGRES_DB: ${POSTGRES_DB:-}
      POSTGRES_USER: ${POSTGRES_USER:-}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      SECRET_KEY: ${SECRET_KEY}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-}
      TELEGRAM_AUTH_MAX_AGE_SECONDS: ${TELEGRAM_AUTH_MAX_AGE_SECONDS:-}
      TELEGRAM_WELCOME_MESSAGE: ${TELEGRAM_WELCOME_MESSAGE:-}
      N8N_TG_WELCOME_WEBHOOK_URL: ${N8N_TG_WELCOME_WEBHOOK_URL:-}
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS:-}
      COOKIE_SECURE: ${COOKIE_SECURE:-}
      COOKIE_SAMESITE: ${COOKIE_SAMESITE:-}
      TIMEZONE: ${TIMEZONE:-Europe/Moscow}
      TZ: ${TZ:-Europe/Moscow}
    env_file:
      - .env
