version: "3.9"

services:
  app:
    image: alanwakeking/propusk-system:latest
    container_name: propusk_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL:-}
      POSTGRES_DB: ${POSTGRES_DB:-}
      POSTGRES_USER: ${POSTGRES_USER:-}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      SECRET_KEY: ${SECRET_KEY}
    env_file:
      - .env
